import { ref } from 'vue'

export const projects = ref([
  {
    id: 1,
    title: 'Oz Ensemble',
    description: 'Mobile application designed to help users handling their alcohol consumption',
    pageName: 'Oz',
    logoUrl: 'logos/logo_oz.png',
    technologies: ['React Native', 'PostgreSQL', 'Prisma'],
  },
  {
    id: 2,
    title: 'Jobmaker',
    description: 'Web application focusing on clearing companies employees carreerpath ',
    pageName: 'Jobmaker',
    logoUrl: 'logos/logo_jobmaker.jpg',
    technologies: ['React', 'MongoDB', 'AWS'],
  },
  {
    id: 3,
    title: 'Zurban',
    description: 'Mobile app to reorganise your contacts from all your sources',
    pageName: 'Zurban',
    logoUrl: 'logos/logo_zurban.jpg',
    technologies: ['React Native', 'WatermelonDB'],
  },
  {
    id: 4,
    title: 'PetClub',
    description: 'Sociale mobile app allowing pets to sociabilize',
    pageName: 'PetClub',
    logoUrl: 'logos/logo_petclub.png',
    technologies: ['React Native', 'MongoDB'],
  },
  {
    id: 5,
    title: 'Maison Matrimoniale Gay',
    description: 'Sociale mobile app developed for gay men looking for true relationships',
    pageName: 'MaisonMat',
    logoUrl: 'logos/logo_maison_matrimoniale.jpg',
    technologies: ['React Native', 'Firebase'],
  },
  {
    id: 6,
    title: 'Accounting',
    description: 'Internal web app of Selego, regrouping plenty of accounting features',
    pageName: 'Accounting',
    logoUrl: 'logos/logo_accounting.png',
    technologies: ['React', 'MongoDB', 'CleverCloud'],
  },
  {
    id: 7,
    title: 'Emeis',
    description: 'Web app featuring AI in order to treat admin documents',
    pageName: 'Emeis',
    logoUrl: 'logos/logo_emeis.png',
    technologies: ['React', 'MongoDB', 'CleverCloud'],
  },
])
